

<div class="guest-heading">
<span><?= $block->escapeHtml(__('Or continue as a guest')) ?></span>
</div>
<?php               
$block= $block->getLayout()->createBlock('Vnecoms\Sms\Block\Customer\Register\Mobile'); ?>

<div class="field mobile vsms-field-container required">
<label for="mobile-number" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
<div class="control">
<input type="tel" name="mobile_number_input" id="mobile-number-input-code" value="<?php echo $block->getInitMobileNumber();?>" 
    class="input-text mobile-number required-entry validate-require-other-fields validate-phone-number<?php if($block->isEnabledVerifying()):?> otp-verify<?php endif;?><?php if($block->getIsVerifiedMobile()):?> otp-validated<?php endif;?>" />        
    <label for="mobile-number" class="label message-label"><span><?php /* @escapeNotVerified */ echo __('A verification code will be sent by text message') ?></span></label>   
    <input type="hidden" name="mobile_number" id="mobile-number" />
    <input type="hidden" name="mobile_otp" id="mobile-otp" />
</div>
</div>

<div class="sms-code-dialog" id="sms-code-dialog">
<div class="sms-code-step-1">
<span class="sms-otp-mobile-code"></span>
<button class="action primary send-otp-btn" id="send-otp-btn"><span><?php echo __("Send the verification code")?></span></button>
</div>
<div class="sms-code-step-2">
<span><?php echo __("Please enter the verification code sent to",$block->getOtpLength())?><span class="sms-otp-mobile-code"></span> </span>
<input type="text" name="sms_otp_code" id="sms-otp-input" value="" class="input-text required-entry" placeholder="<?php echo __("Verification code")?>"/>
<button class="action primary send-otp-btn" id="verify-otp-btn"><span><?php echo __("Confirmation")?></span></button>
<a href="#" class="resend-otp-btn" id="resend-otp-btn" data-time="<?php echo $block->getOtpResendPeriodTime()?>"><?php echo __("Resend after %1 seconds ", $block->getOtpResendPeriodTime())?></a>
</div>
</div>

<script type="text/javascript">
var URL_SEND_OTP = '<?php echo $block->getSendOtpUrl();?>';
var URL_VERIFY_OTP = '<?php echo $block->getVerifyOtpUrl();?>';

require([
'jquery',
'Magento_Ui/js/modal/modal',
'Vnecoms_Sms/js/utils',
'jquery/intltellinput',
'jquery/mask',
'mage/mage',
'mage/validation',
'loader',
'domReady!'
], function($, modal){


function initMobileInput(){
    $("#mobile-number-input-code").intlTelInput({
        initialCountry: '<?php echo strtolower($block->getInitialCountry());?>',
        allowDropdown: <?php echo strtolower($block->getAllowCountryDropdown());?>,
    <?php if($block->getInitialCountry() == 'auto'):?>
        geoIpLookup: function(callback) {
            $.get("<?php echo $block->getGeoIpUrl()?>", function() {}, "jsonp").always(function(resp) {
            var countryCode = (resp && resp.country) ? resp.country : "";
            callback(countryCode);
            });
        },
    <?php endif;?>
    onlyCountries: <?php echo $block->getOnlyCountries();?>,
    preferredCountries:<?php echo $block->getPreferredCountries();?>
    }).done(function() {
        initMask();
    $('#mobile-number').val($("#mobile-number-input-code").intlTelInput("getNumber"));
    $('#mobile-number-input-code').on('keyup', function() {
        validatePhoneNum();
    }).on("countrychange", function(e, countryData) {
            validatePhoneNum();
            initMask();
    });
    });
}

function initMask(){
    var countryData = $("#mobile-number-input-code").intlTelInput("getSelectedCountryData");
    if(!countryData.iso2) return false;
    var numberType = intlTelInputUtils.numberType['MOBILE'];
    var mask = intlTelInputUtils.getExampleNumber(countryData.iso2, true, numberType);
    $("#mobile-number-input-code").mask(mask.replace(/([0-9])/g, '0'));
}



function sendOtp(isResend){
    $.ajax({
        url: URL_SEND_OTP,
        method: "POST",
        data: {
            mobile : $("#mobile-number").val(),
            resend : isResend,
        },
        dataType: "json"
        }).done(function( response ){
            if(response.success){
                $('.sms-code-step-1').hide();
                $('.sms-code-step-2').show();
                $('#mobile-number-id').val(response.mobile_id);
                runCountDown();
            }else{
                //console.log("something went wrong");
                alert("something went wrong");
            }
            
    });
}
initMobileInput();

 
function runCountDown(){
    var resendBtn = $('#resend-otp-btn');
    if(!resendBtn.hasClass('running')){
        resendBtn.addClass('running');
    }

    if(!resendBtn.data('couting')){
        !resendBtn.data('couting', resendBtn.data('time'));
    }
    var count = parseInt(resendBtn.data('couting'));
    count --;
    resendBtn.data('couting', count);
    resendBtn.html('<?php echo __("Resend after %1 seconds")?>'.replace('%1', count));

    if(count == 0) {
        resendBtn.removeClass('running');
        resendBtn.html('<?php echo __("Resend OTP")?>');
        return;
    }
    setTimeout(function(){runCountDown()}, 1000);
}

function validatePhoneNum(){
    var number = $("#mobile-number-input-code").intlTelInput("getNumber");
    var currentCustomerNumber = '<?php echo $block->getCustomer()->getMobilenumber()?>';
    //console.log(currentCustomerNumber);
    if(currentCustomerNumber.length && (number == currentCustomerNumber)){
        $('#mobile-number-input-code').addClass('otp-validated');
    }else{
        $('#mobile-number-input-code').removeClass('otp-validated');
    }
    
    $('#mobile-number').val(number);
    $('.sms-otp-mobile-code').html($("#mobile-number-input-code").intlTelInput("getNumber", intlTelInputUtils.numberFormat.INTERNATIONAL)); /*intlTelInputUtils.numberFormat.NATIONAL*/
}

$('#send-otp-btn').click(function(){
   var check= $("#mobile-number").val();
   setTimeout(function(){
                        
        var errortext = jQuery("#phone-number-form").find("#mobile-number-input-code-error").text();
        
        if(errortext != "<?php echo __('The mobile number is not valid.'); ?>" && errortext != "<?php echo __('This is a required field.') ?>")
        {
            //$(".validate-phone-number2").attr("readonly","readonly");
            document.activeElement.blur();
            sendOtp2(0);
            //$('#sms-otp-dialog').modal('closeModal');    
        }
        
    },1000);
});

    $('#resend-otp-btn').click(function(){
        if($('#resend-otp-btn').hasClass('running')){
            return false;
        }
        sendOtp(1);
        return false;
    });

    $('#verify-otp-btn').click(function(){
    $('#sms-otp-error').remove();
    if($(this).hasClass('verifying')){
        return;
    }
    var otp = $('#sms-otp-input').val();
    if(!otp){
        $('#sms-otp-input').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input"><?php echo __("This is required field.");?></div>');
        return;
    }
    
    $(this).addClass('verifying');
    
    $.ajax({
    url: URL_VERIFY_OTP,
    method: "POST",
    data: {
        mobile : $("#mobile-number").val(),
        otp: otp
    },
    dataType: "json"
    }).done(function( response ){
        $('#verify-otp-btn').removeClass('verifying');
        $('#sms-otp-input').val('');
        if(response.success){
            $("#mobile-otp").val(response.otp);
            $('#mobile-number-input-code').addClass('otp-validated').validation().validation('isValid');
            alert("work");
        }else{
            $('#sms-otp-input').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input">'+response.msg+'</div>');
        }
        
    });
});

var rules = {
'validate-phone-number': [
    function (value, element) {
        return $(element).intlTelInput("isValidNumber");
    },
    '<?php echo __("The mobile number is not valid.")?>'
    ],
    'otp-verify': [
        function (value, element) {
            var isValid = true;
            var elements = $(element).parents('form').find('input,select,textarea');
            elements.each(function(index, elm){
                if($(elm).is(":hidden") || elm == element) {return true};
                isValid = (isValid && $.validator.validateElement(elm));
            });
            if(!isValid) return false;
                            
            if(!$(element).hasClass('otp-validated')){
                $('.sms-code-step-1').show();
                $('.sms-code-step-2').hide();
                $('#sms-otp-dialog').modal('openModal');
                return false;
            }
            return true;
        },
        ''
    ],
};
$.each(rules, function (i, rule) {
    rule.unshift(i);
    $.validator.addMethod.apply($.validator, rule);
});

});
</script>







