<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
         $customerSession = $objectManager->get('Magento\Customer\Model\Session');
         if($customerSession->isLoggedIn() ) {
                 header("Location: /customer/account/");
                 exit();
          }

$url = $block->getLayout()->createBlock('Custom\Checkoutform\Block\Url');
$guest = $block->getLayout()->createBlock('Custom\Checkoutform\Block\Session');
$block= $block->getLayout()->createBlock('Magento\Customer\Block\Form\Login');
?>
<script>
require([
        'jquery','mage/url', 'jquery/ui', 'jquery/validate', 'mage/translate', 'mage/mage','jquery/jquery.cookie'
    ], function($, url){
        $( document ).ready(function() {

            if (window.location.href.indexOf('?name=tab2') > 0) {
              $('.login-class').removeClass('active');
              $('.register-class').addClass('active');
              $('#tab1').removeClass('active in');
              $('#tab2').addClass('active in');
           }
        });
    });
</script>
<div class="res-login-tab">
      <ul class="nav nav-tabs">
        <li class="active login-class"><a data-toggle="tab" href="#tab1" id="logintab"><?= $block->escapeHtml(__('Log In')) ?></a></li>
        <li class="register-class"><a data-toggle="tab" href="#tab2" id="registertab"><?= $block->escapeHtml(__('New account')) ?></a></li>
      </ul>

      <div class="tab-content">
        <div id="tab1" class="tab-pane fade login-class in active">
        <div class="block block-customer-login">
             <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
              action="<?= $block->escapeUrl($url->getLoginActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" placeholder="<?= $block->escapeHtml(__('Enter the email address (required)')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" placeholder="<?= $block->escapeHtml(__('Enter the password (required)')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    <div class="primary"><button type="submit" class="action login primary black-btn" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<?php
//$guest_code =  $guest->getGuest();
$flag = 0;
$params = $block->getRequest()->getParams();
if (isset($params['account'])) {
    $flag = 1;
}
//$guest_remove =  $guest->unSetGuest();
?>
    <form name="phone-number-form" id="phone-number-form" <?php if($flag){ ?> style="display:none" <?php } ?> class="custom-phone-validate"  method="post" enctype="multipart/form-data" autocomplete="off">
    <div class= "custom-phone-validate">
    <div class="guest-heading">
                <span><?= $block->escapeHtml(__('Or continue as a guest')) ?></span>
    </div>
            <?php
                $block= $block->getLayout()->createBlock('Vnecoms\Sms\Block\Customer\Register\Mobile'); ?>
    <div class="guest-wrapper">
            <div class="field mobile vsms-field-container required">
                <div class="control">
                <input type="tel" name="mobile_number_input" id="mobile-number-input-code" placeholder="<?php /* @escapeNotVerified */ echo __('Enter the mobile number (required)') ?>" value="<?php echo $block->getInitMobileNumber();?>"
                    class="input-text mobile-number required-entry validate-require-other-fields validate-phone-number2<?php if($block->isEnabledVerifying()):?> otp-verify<?php endif;?><?php if($block->getIsVerifiedMobile()):?> otp-validated<?php endif;?>" />
                    <label for="mobile-number" class="label message-label"><span><?php /* @escapeNotVerified */ echo __('A verification code will be sent by text message') ?></span></label>
                    <input type="hidden" name="mobile_number" id="mobile-number" />
                    <input type="hidden" name="mobile_otp" id="mobile-otp" />
                 </div>
            </div>

        <div class="sms-code-dialog otp-div-login" id="sms-code-dialog">
            <div class="sms-code-step-1 ">
                <button class="action primary send-otp-btn-code black-btn" id="send-otp-btn-code2"><span><?php echo __("Send the verification code")?></span></button>
            </div>
            <div class="sms-code-step-2" id="last-div">
                <div class="varification-code"><span><?php echo __("Please enter the verification code sent to",$block->getOtpLength())?> </span></div>
                <input type="tel" inputmode="numeric" name="sms_otp_code" id="sms-otp-input-code" value="" class="input-text required-entry" placeholder="<?php echo __("Verification code")?>"/>
                <button class="action primary send-otp-btn-code red-btn" id="verify-otp-btn-code"><span><?php echo __("Confirmation")?></span></button>
                <a href="#" class="resend-otp-btn-code login-as-guest" id="resend-otp-btn-code2" data-time="<?php echo $block->getOtpResendPeriodTime()?>"><?php echo __("Resend after %1 seconds ", $block->getOtpResendPeriodTime())?></a>
            </div>
        </div>
    </div>
</div>

</form>

        <script type="text/javascript">
            var URL_SEND_OTP = '<?php echo $block->getSendOtpUrl();?>';
            var URL_VERIFY_OTP = '<?php echo $block->getVerifyOtpUrl();?>';

            require([
                'jquery',
                'Magento_Ui/js/modal/modal',
                'Vnecoms_Sms/js/utils',
                'jquery/intltellinput',
                'jquery/mask',
                'mage/mage',
                'mage/validation',
                'loader',
                'domReady!'
            ], function($, modal){

                function initMobileInput2(){
                    $("#mobile-number-input-code").intlTelInput({
                        initialCountry: '<?php echo strtolower($block->getInitialCountry());?>',
                        allowDropdown: <?php echo strtolower($block->getAllowCountryDropdown());?>,
                    <?php if($block->getInitialCountry() == 'auto'):?>
                        geoIpLookup: function(callback) {
                            $.get("<?php echo $block->getGeoIpUrl()?>", function() {}, "jsonp").always(function(resp) {
                            var countryCode = (resp && resp.country) ? resp.country : "";
                            callback(countryCode);
                            });
                        },
                    <?php endif;?>
                    onlyCountries: <?php echo $block->getOnlyCountries();?>,
                    preferredCountries:<?php echo $block->getPreferredCountries();?>
                    }).done(function() {
                        initMask2();
                    $('#mobile-number').val($("#mobile-number-input-code").intlTelInput("getNumber"));
                    $('#mobile-number-input-code').on('keyup', function() {
                        validatePhoneNum2();
                    }).on("countrychange", function(e, countryData) {
                            validatePhoneNum2();
                            initMask2();
                    });
                    });
                }

                function initMask2(){
                    var countryData = $("#mobile-number-input-code").intlTelInput("getSelectedCountryData");
                    if(!countryData.iso2) return false;
                    var numberType = intlTelInputUtils.numberType['MOBILE'];
                    var mask = intlTelInputUtils.getExampleNumber(countryData.iso2, true, numberType);
                    $("#mobile-number-input-code").mask(mask.replace(/([0-9])/g, '0'));
                }


                function sendOtp2(isResend){
                    $('#sms-otp-dialog').modal('closeModal');
					//console.log("asd");
                    $.ajax({
                        url: URL_SEND_OTP,
                        method: "POST",
                        data: {
                            mobile : $("#mobile-number").val(),
                            resend : isResend,
                        },
                        dataType: "json"
                        }).done(function( response ){
                            if(response.success){
                              //  $('#sms-otp-dialog').modal('closeModal');
                                $('.sms-code-step-1').hide();
                                $('.sms-code-step-2').show();

                                $('#mobile-number-id').val(response.mobile_id);
                                runCountDown2();

                                //alert("hello2");
                                var scrWidth = screen.width;
                                if(scrWidth <= 1023)
                                {
                                    $('html, body').animate({
                                        scrollTop: $(".otp-div-login").offset().top
                                    }, 100);
                                }

                            }else{
                                //console.log("something went wrong");
                                alert("something went wrong");
                            }

                    });
                }
                initMobileInput2();


                function runCountDown2(){
                    console.log("resenddd");
                    var resendBtn = $('#resend-otp-btn-code2');
                    if(!resendBtn.hasClass('running')){
                        console.log("addd");
                        resendBtn.addClass('running');
                        console.log("ysk");
                    }

                    if(!resendBtn.data('couting')){
                        !resendBtn.data('couting', resendBtn.data('time'));
                    }
                    var count = parseInt(resendBtn.data('couting'));
                    count --;
                    resendBtn.data('couting', count);
                    resendBtn.html('<?php echo __("Resend after %1 seconds")?>'.replace('%1', count));

                    if(count == 0) {
                        resendBtn.removeClass('running');
                        resendBtn.html('<?php echo __("Resend Code")?>');
                        return;
                    }
                    setTimeout(function(){runCountDown2()}, 1000);
                }

                function validatePhoneNum2(){
                    var number = $("#mobile-number-input-code").intlTelInput("getNumber");
                    var currentCustomerNumber = '<?php echo $block->getCustomer()->getMobilenumber()?>';
                    //console.log(currentCustomerNumber);
                    if(currentCustomerNumber.length && (number == currentCustomerNumber)){
                        $('#mobile-number-input-code').addClass('otp-validated');
                    }else{
                        $('#mobile-number-input-code').removeClass('otp-validated');
                    }

                    $('#mobile-number').val(number);
                    $('.sms-otp-mobile-code').html($("#mobile-number-input-code").intlTelInput("getNumber", intlTelInputUtils.numberFormat.INTERNATIONAL)); /*intlTelInputUtils.numberFormat.NATIONAL*/
                }

                $('#send-otp-btn-code2').click(function(){

                    setTimeout(function(){

                        var errortext = jQuery("#phone-number-form").find("#mobile-number-input-code-error").text();

                        if(errortext != "<?php echo __('The mobile number is not valid.'); ?>" && errortext != "<?php echo __('This is a required field.') ?>")
                        {
							console.log("asd");
                            document.activeElement.blur();
                            sendOtp2(0);
                            //$('#sms-otp-dialog').modal('closeModal');
                        }

                    },1000);


                });

                    $('#resend-otp-btn-code2').click(function(){
                        if($('#resend-otp-btn-code2').hasClass('running')){
                            return false;
                        }
                        sendOtp2(1);
                        return false;
                    });

                    $('#verify-otp-btn-code').click(function(){
                    $('#sms-otp-error').remove();
                    if($(this).hasClass('verifying')){
                        return;
                    }
                    var otp = $('#sms-otp-input-code').val();
                    if(!otp){
                        $('#sms-otp-input-code').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input-code"><?php echo __("This is required field.");?></div>');
                        return;
                    }

                    $(this).addClass('verifying');

                    $.ajax({
                    url: URL_VERIFY_OTP,
                    method: "POST",
                    data: {
                        mobile : $("#mobile-number").val(),
                        otp: otp
                    },
                    dataType: "json"
                    }).done(function( response ){
                        $('#verify-otp-btn-code').removeClass('verifying');
                        $('#sms-otp-input-code').val('');
                        //console.log(response);
                        if(response.success){
                                localStorage.setItem('reg_mobile', $("#mobile-number-input-code").val());
                                window.location.href = "/checkout";
                        }else{
                            $('#sms-otp-input-code').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input-code">'+response.msg+'</div>');
                        }

                    });
                });

                var rules = {
                'validate-phone-number2': [
                    function (value, element) {

                        return $(element).intlTelInput("isValidNumber");
                    },
                    '<?php echo __("The mobile number is not valid.")?>'
                    ],
                    'otp-verify': [
                        function (value, element) {
                            var isValid = true;

                            var elements = $(element).parents('form').find('input,select,textarea');
                            elements.each(function(index, elm){
                                if($(elm).is(":hidden") || elm == element) {return true};
                                isValid = (isValid && $.validator.validateElement(elm));
                            });
                            if(!isValid) return false;
                            if(!$(element).hasClass('otp-validated')){
                                $('.sms-code-step-1').show();
                                $('.sms-code-step-2').hide();
                                var curtab = $(document).find("#logintab").parent().hasClass("active");
                                if(curtab)
                                {
                                    $('#sms-otp-dialog').modal('closeModal');
                                }
                                return false;
                            }

                            return true;
                        },
                        ''
                    ],
                };
                $.each(rules, function (i, rule) {
                    rule.unshift(i);
                    $.validator.addMethod.apply($.validator, rule);
                });

            });
        </script>

</div>
        <div id="tab2" class="tab-pane register-class fade">
        <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$block= $block->getLayout()->createBlock('Magento\Customer\Block\Form\Register');


?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($url->getRegisterActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info">
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php if ($_dob->isEnabled()) : ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_taxvat->isEnabled()) : ?>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()) : ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()) : ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
            <?php if ($_company->isEnabled()) : ?>
                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php if ($_telephone->isEnabled()) : ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
            <?php if ($_fax->isEnabled()) : ?>
                <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
            <?php endif ?>
            <?php //phpcs:disable ?>
            <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
            <?php //phpcs:enable ?>
            <div class="field street required">
                <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php //phpcs:disable ?>
                        <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
                        <?php //phpcs:enable ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $block->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable ?>
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <?php //phpcs:disable ?>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable ?>
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes) : ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

        <div class="field password required">
            <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
<?php /* ?>
        <div class="field telephone required">
    <label for="telephone" class="label">
        <span class="register_label">
            <?= $block->escapeHtml(__('Mobile')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('fax')
            );
        ?>
        <div class="code">
        <input type="text"
              name="mobilecode"
              id="mobilecode"
              value="+966"
              class="input-text no-whitespace validate-length"
               data-validate="{required:true,'validate-length':true}"
        >
        </div>
        <div class="mobile-number">
        <input type="text"
               name="phone_number"
               id="phone_number"
               maxlength="10"
               placeholder="+966XXXXXXXX"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text no-whitespace validate-length maximum-length-10 minimum-length-10 mobiletendigit register_input <?= $_validationClass ?: '' ?>"
               data-validate="{required:true,'validate-length':true}"
        ></div>
          <span class="telephone_span_error"></span>
         <div role="alert" aria-live="assertive" class="error-container">
              <small class="error error-invalid">
                  Please enter a valid phone number. Example : +966XXXXXXXXX
              </small>
          </div>
    </div>
</div>
<?php */ ?>
        <div class="custom-phone-validate">
            <?php echo $this->getChildHtml('customer-number-html'); ?>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action createaccount submit primary black-btn" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('register')) ?></span></button>
        </div>
    </div>
</form>
        </div>
      </div>
</div>

<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()) : ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else : ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

    var dataForm2 = $('#phone-number-form');
    var ignore = null;

    dataForm2.mage('validation',
    {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()) : ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                <?php //phpcs:disable ?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable ?>
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                <?php //phpcs:disable ?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
 <script type="text/javascript">
    require([
        'jquery', 'jquery/ui', 'jquery/validate', 'mage/translate', 'mage/mage'
    ], function($){
          $(document).ready(function(){
            $('.actions-toolbar .createaccount').trigger('processStart');

                $('#phone_number').keypress(function (event) {
            var keycode = event.which;
            if (!(event.shiftKey == false && (keycode == 46 || keycode == 8 || keycode == 37 || keycode == 39 || (keycode >= 48 && keycode <= 57)))) {
                event.preventDefault();

            }
            validationPhonenumber(this);
        });
    });
});

    // /* Scripts to run at page start - BEGIN */
    //      //   prefixPhonenumber($("#telephone"));



    //         /* Scripts to run at page start - END */

    //         $(document).on("focusout","#phone_number", function(e){

    //           // if($(this).val() == ""){
    //           //   prefixPhonenumber(this);


    //           // }else{
    //           //   validatePhone(this);
    //           // }
    //           validationPhonenumber(this);

    //         });

    //         $(document).on("keypress","#phone_number",function(e){
    //           if(window.event) { // IE
    //                 keynum = e.keyCode;
    //             } else if(e.which){ // Netscape/Firefox/Opera
    //                 keynum = e.which;
    //             }

    //             if(keynum < 48 || keynum > 57){
    //               return false;
    //             }

    //             if($(this).val().length <= 3){
    //               return false;
    //             }
    //             validationPhonenumber(this);

    //         });
    //         $(document).on("keyup","#phone_number",function(e){
    //           validationPhonenumber(this);
    //         });
    //         $(document).on("keydown","#phone_number",function(e){
    //           validationPhonenumber(this);
    //         });
    //         $(document).on("change","#phone_number", function(e){

    //           // if($(this).val() == ""){
    //           //   prefixPhonenumber(this);


    //           // }else{
    //           //   validatePhone(this);
    //           // }
    //           validationPhonenumber(this);

    //         });

    //         function prefixPhonenumber(ele){
    //           var value=$(ele).val();
    //           // if($(ele).val()  == ""){
    //           //          $(ele).val("+966");
    //           // }
    //           // else{
    //           //   validationPhonenumber(this);
    //           // }
    //         }

            function validationPhonenumber(ele){
              var value = $(ele).val();
              console.log(value);
                var re = /^(009665|9665|\+9665|05|5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$/.test(value);
                // if(re == false) {
                // console.log(re);
                //     $(".telephone_span_error").text("Number invalid");
                //     $('.custom-register-btn').attr('disabled','disabled');
                // }
                // else if(re == true) {
                //     console.log(re);
                //     $(".telephone_span_error").text("");
                //     $('.custom-register-btn').removeAttr('disabled');
                // }preg_match('/^(055)([0-9])$/', '0525330609')
                console.log(re);
            }
    //         function validatePhone(ele){

    //           var phone = $(ele).val();
    //           // if(phone.length < 4){
    //           //   $(ele).val("");
    //           // }
    //           // else{
    //           // console.log(phone);

    //           //   var str = phone[0] + phone[1] + phone[2] + phone[3];
    //           //   // alert(str != "+966");
    //           // console.log(str);

    //           //   if(str != "+  "){
    //           //     phone = phone.replace('+','');
    //           //     $(ele).val("+966" + phone);
    //           //   }
    //           // }
    //         }

    //     });

    // });
</script>
<style>
  .telephone_span_error{
    color: red;
    font-size: 12px;
    font-weight: 500;
  }
</style>
