<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add To Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
	$total_stock = 0;
	if($_product->getTypeID() == 'configurable'){
		$productTypeInstance = $_product->getTypeInstance();
		$usedProducts = $productTypeInstance->getUsedProducts($_product);
		foreach ($usedProducts as $simple) {
			$total_stock += $StockState->getStockQty($simple->getId(), $simple->getStore()->getWebsiteId());
		}
	} else {
		$total_stock = $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
	}
?>

	<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

	<?php // If is deals product. Show countdown time ?>
	<?php if($_product->getSpecialPrice() && $_product->getSpecialToDate() && $_product->getSpecialFromDate()): ?>

		<?php $dateTimeFormat = \Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT; ?>
		<?php $now = $themeHelper->getCurrentDateTime(); ?>
		<?php $specialFromDate = date($dateTimeFormat, strtotime($_product->getSpecialFromDate())); ?>
		<?php $specialToDate = date($dateTimeFormat, strtotime($_product->getSpecialToDate())); ?>

		<?php if($specialFromDate <= $now && $specialToDate > $now): ?>
			<div class="product-detail-deals margin-top25">
				<?php if ($total_stock<6): ?>
					<div class="hurry-text text-uppercase"><?php echo __('Hurry! Only %1 left in stock', $total_stock); ?></div>
				<?php endif ?>
				<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
			</div>
		<?php endif ?>

	<?php endif ?>
	<?php // End Deals ?>
	<?php if($_product->getTypeID() == 'configurable'): ?>
		<?php if ($total_stock > 0){ ?>
			<div class="box-tocart">
				<?php echo $block->getChildHtml('', true) ?>
				<div class="fieldset">
				<div class="custom">
					<div class="custom_box">
						<div class="title1">
							<p class="title1">متوفرة</p>
						</div>
						<?php /*
								$attribute = $_product->getResource()->getAttribute('delivery_tim');
								$value = $attribute->getFrontend()->getValue($_product);
							?>
						<?php if($value!=false): ?>
						<div class="deliver_time">
							<span class="saudi-flag-icon"><img src='<?php echo $this->getViewFileUrl('images/flags/sa.png'); ?>' alt="<?= __('SA Flag') ?>"></span>
							<label>
								<?= $value ?>
							</label>
						</div>
						<?php endif; */?>
						<div class="title2">
	                <p class="title2"> أسرع! متبقي عدد 3 حبات فقطٍ</p>
						</div>
				    </div>
					<?php if ($block->shouldRenderQuantity()): ?>
					<div class="field qty">
					<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
					<div class="control">
						<span class="edit-qty minus" onclick="minusQty('qty')">-</span>
						<input type="number"
							name="qty"
							id="qty"
							maxlength="12"
							value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
							title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
							data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
							/>
						<div class="qty-after"></div>
						<div class="wrapper-edit-qty">
							<div class="wrapper-qty">
								<div class="title">
									<p><?php /* @escapeNotVerified */ echo __('Quantity') ?></p>
									<button type="button">x</button>
								</div>
								<div class="content">
								<?php

									$qtyPro = $_product->getExtensionAttributes()->getStockItem()->getQty();
									if ($qtyPro > 10) {
										$qtyPro = 10;
									}
									$html = "";
									for ($x = 1; $x <= 4; $x++) {
										if( $x == 1 ) {
											$html .="<div class='item-qty active' data-value='".$x."'>" .$x.  "</div>";
										} else {
											$html .="<div class='item-qty' data-value='".$x."'>".$x."</div>";
										}
									}
									echo $html;
								?>
								</div>
							</div>
						</div>
						<span class="edit-qty plus" onclick="plusQty('qty')">+</span>
					</div>
				</div>
					<?php endif; ?>
				</div>
				<?= $this->helper("Amasty\Mostviewed\Helper\Render")->renderCurrentPack() ?>
					<div class="actions">
						<button type="submit"
								title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
								class="action primary tocart"
								id="product-addtocart-button">
							<span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
						</button>
						<?php
						$buyNowHtml = $this->getLayout()
								->createBlock('Magento\Catalog\Block\Product\View')
								->setTemplate('Mageprince_BuyNow::buynow-view.phtml')
								->toHtml();
						//echo $buyNowHtml;
						?>
							<?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("CheckoutCom_Magento2::cart/applepay.phtml")->toHtml();?>

						<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
							$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
							if($currencyCode == "SAR"){
								echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_popup')->toHtml();
							}
						if($currencyCode == "BHD"){
								echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_popup_bhd')->toHtml();
							} ?>
						<?php
							$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
							$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
						?>
					</div>
				</div>

				<div class="actions action-add-to">
					<?php if ($themeHelper->getStoreConfig('mpanel/product_details/wishlist') && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
						<button type="button" class="action towishlist"
							data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
							data-action="add-to-wishlist"
							title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
								<span class="pe-7s-like"></span>
						</button>
						<script type="text/x-magento-init">
							{
								"body": {
									"addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
								}
							}
						</script>
					<?php endif; ?>

					<?php if($themeHelper->getStoreConfig('mpanel/product_details/compare')): ?>
						<button type="button" class="action tocompare"
							data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
							data-role="add-to-links"
							title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
								<span class="pe-7s-graph3"></span>
						</button>
					<?php endif ?>

					<?php if ($block->canEmailToFriend()): ?>
						<button type="button" onclick="setLocation('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>')"
					class="action mailto friend" title="<?php /* @escapeNotVerified */ echo __('Send Email to Friend') ?>"><span class="pe-7s-mail"></span></button>
					<?php endif; ?>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>
		<?php }else { ?>
			<div class="title1">
				<p class="title1">إنتهى من المخزن</p>
			</div>
		<?php } ?>
	<?php else: ?>


		<div class="box-tocart">
			<?php echo $block->getChildHtml('', true) ?>

			<div class="fieldset">
				<?php if ($block->shouldRenderQuantity()): ?>
				<div class="field qty">
					<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
					<div class="control">
						<span class="edit-qty minus" onclick="minusQty('qty')">-</span>
						<input type="number"
							name="qty"
							id="qty"
							maxlength="12"
							value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
							title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
							data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
							/>
						<div class="qty-after"></div>
						<div class="wrapper-edit-qty">
							<div class="wrapper-qty">
								<div class="title">
									<p><?php /* @escapeNotVerified */ echo __('Quantity') ?></p>
									<button type="button">x</button>
								</div>
								<div class="content">
								<?php

									$qtyPro = $_product->getExtensionAttributes()->getStockItem()->getQty();
									if ($qtyPro > 10) {
										$qtyPro = 10;
									}
									$html = "";
									for ($x = 1; $x <= 4; $x++) {
										if( $x == 1 ) {
											$html .="<div class='item-qty active' data-value='".$x."'>" .$x.  "</div>";
										} else {
											$html .="<div class='item-qty' data-value='".$x."'>".$x."</div>";
										}
									}
									echo $html;
								?>
								</div>
							</div>
						</div>
						<span class="edit-qty plus" onclick="plusQty('qty')">+</span>
					</div>
				</div>
				<?php endif; ?>
				<?= $this->helper("Amasty\Mostviewed\Helper\Render")->renderCurrentPack() ?>
				<div class="actions">
					<button type="submit"
							title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
							class="action primary tocart"
							id="product-addtocart-button">
						<span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
					</button>
					<?php
					$buyNowHtml = $this->getLayout()
							->createBlock('Magento\Catalog\Block\Product\View')
							->setTemplate('Mageprince_BuyNow::buynow-view.phtml')
							->toHtml();
					//echo $buyNowHtml;
					?>
						<?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("CheckoutCom_Magento2::cart/applepay.phtml")->toHtml();?>

					<?php
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
						$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
						if($currencyCode == "SAR"){
							echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_popup')->toHtml();
						}
					if($currencyCode == "BHD"){
							echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_popup_bhd')->toHtml();
						} ?>
					<?php
						$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
						$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
					?>
				</div>
			</div>
			<div class="actions action-add-to">
				<?php if ($themeHelper->getStoreConfig('mpanel/product_details/wishlist') && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
					<button type="button" class="action towishlist"
						data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
						data-action="add-to-wishlist"
						title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
							<span class="pe-7s-like"></span>
					</button>
					<script type="text/x-magento-init">
						{
							"body": {
								"addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
							}
						}
					</script>
				<?php endif; ?>

				<?php if($themeHelper->getStoreConfig('mpanel/product_details/compare')): ?>
					<button type="button" class="action tocompare"
						data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
						data-role="add-to-links"
						title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
							<span class="pe-7s-graph3"></span>
					</button>
				<?php endif ?>

				<?php if ($block->canEmailToFriend()): ?>
					<button type="button" onclick="setLocation('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>')"
				class="action mailto friend" title="<?php /* @escapeNotVerified */ echo __('Send Email to Friend') ?>"><span class="pe-7s-mail"></span></button>
				<?php endif; ?>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
	<?php endif ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($block->shouldRenderQuantity()): ?>
	<script type="text/javascript">
		function plusQty(qtyInput){
			require([
			'jquery'
			], function(jQuery){
				(function($) {
					if($('#'+qtyInput).attr('disabled')!='disabled'){
						qty = $('#'+qtyInput).attr('value');
						qty = parseInt(qty);
						qty++;
						$('#'+qtyInput).val(qty);
					}
				})(jQuery);
			});
		}
		function minusQty(qtyInput){
			require([
			'jquery'
			], function(jQuery){
				(function($) {
					if($('#'+qtyInput).attr('disabled')!='disabled'){
						qty = $('#'+qtyInput).attr('value');
						qty = parseInt(qty);

						if(qty>1){
							qty--;
							$('#'+qtyInput).val(qty);
						}
					}
				})(jQuery);
			});
		}
	</script>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery',
		'Magento_Ui/js/modal/modal'
    ], function($, modal){
						$(window).load(function() {
							$("#product-addtocart-button").removeAttr("style");
				});



		$( ".catalog-product-view .field.qty>.control .qty-after").click(function() {

			$(".wrapper-edit-qty").toggleClass("active");
			if($(".wrapper-edit-qty").hasClass("active")) {
				$(".scroll-to-top").addClass("active-pro");
			} else {
				$(".scroll-to-top").removeClass("active-pro");
			}
		});
		$( ".catalog-product-view .wrapper-qty .title button" ).click(function(e) {
			e.preventDefault();
			e.stopPropagation();
			$(".wrapper-edit-qty").removeClass("active");
			if($(".wrapper-edit-qty").hasClass("active")) {
				$(".scroll-to-top").addClass("active-pro");
			} else {
				$(".scroll-to-top").removeClass("active-pro");
			}
		});
		$( ".catalog-product-view .wrapper-qty .item-qty" ).click(function(e) {
			e.preventDefault();
			e.stopPropagation();

			$(".wrapper-qty .item-qty").removeClass("active");
			$(this).addClass("active");
			var value = $(this).attr("data-value");
			qty = parseInt(value);
			$('#qty').val(qty);
			$(".catalog-product-view .wrapper-qty .title button").trigger("click");
		});

		 var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
				modalClass: 'shippingpopup',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
		$('#businespopup').on("click", function(){
			$("#popup-modal").modal("openModal");
		});
    });
</script>

<style type="text/css">

	.product-info-main .product-add-form .amrelated-pack-wrapper {
		margin-bottom: 17px;
		clear: both;
		border: 2px solid #231F20;
		border-radius: 5px;
		padding: 0 20px 0 20px;
		margin-top: 10px;
}

.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
    font-family: 'LoewNext Medium';
    color: #33313B;
    font-size: 15px;
    position: relative;
}

.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-item.-wide.-main ,
.product-info-main .amrelated-content-wrapper .amrelated-summary-content{
    display: none;
}

.product-info-main .amrelated-content-wrapper .amrelated-pack-list {
    max-width: 100%;
    display: block;
    width: 100%;
    text-align: left;
}

.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-items {
    max-width: 100% !important;
    width: 100% !important;
    background: transparent !important;
}

.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-items .amrelated-pack-item {
    padding: 5px 0;
    width: 100%;opacity: 1 !important;
}
.product-info-main .amrelated-pack-item{
	 padding: 5px 0;

}
.product-info-main .amrelated-pack-item.-collapsed .amrelated-photo,
.product-info-main .amrelated-pack-item.-collapsed .product-reviews-summary.short,
.product-info-main .amrelated-pack-item.-collapsed .price-box {
    display: block;
    margin: auto;
}


.product-info-main .amrelated-content-wrapper .amrelated-pack-list  .amrelated-background {
     background: transparent !important;
}

.product-info-main .amrelated-content-wrapper {
  border-top: 1px solid rgb(35, 31, 32);
    margin: 0;
    padding-top: 20px !important;
    padding: 14px;
    background: transparent;
    width: 100%;
    box-shadow: none;
        display: none;
}
.open--tab {
    display: block !important;
}

.amrelated-title.open--accordian .arrow-title {
    transform: rotate(
270deg
 ) !important;
}
.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-items .amrelated-photo-container {
    width: 70px;
    min-width: 70px;
    height: 70px;
    margin-left: 18px;
    position: relative;
    background: #fff;
    border: 1px solid #e8e8e8;
    margin: 0;

}
.product-info-main .amrelated-content-wrapper  .amrelated-info {
    display: -webkit-flex !important;
    display: -ms-flexbox;
    display: flex !important;
    text-align: left;
        margin-left: 15px;align-items: center;
}


.product-info-main  .amrelated-photo-container .amrelated-checkbox+.amrelated-label {
top: 23px;
    left: -30px;
    width: 19px;
    height: 19px;
    border: 2px solid #0e0e0e;
    border-radius: 4px;


}

.product-info-main  .amrelated-pack-wrapper .amrelated-content-wrapper .amrelated-photo-container .amrelated-discount {
         font-size: 10px;
    padding: 0 4px;
    position: absolute;
    top: -10px;
    right: -10px;
    transform: unset !important;
    width: 50px;
    left: auto !important;
    margin: auto;
    opacity: 0;
}

.product-info-main .amrelated-pack-wrapper .amrelated-name a {
    font-family: 'LoewNext Medium';
    color: #33313B;
    font-size: 14px;
    display: block;
    line-height: 18px;
}

.product-info-main .amrelated-pack-item .amrelated-details .price-box span {
    font-size: 13px !important;
    margin: 0 !important;
}.product-info-main .amrelated-pack-item .amrelated-details .price-box{
	margin-top: 7px;
	display: block;
}
.product-info-main .amrelated-pack-item .amrelated-details {
      margin-left: 20px !important;
    align-items: center;
    display: block;
}
.product-info-main .amrelated-photo-container .amrelated-checkbox:checked+.amrelated-label {
     border-color: #3978bd;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title img {
    width: 15px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    transform: rotate(
90deg
);
    display: block;
    position: absolute;
    right: 0;
    top: 11px;
}

.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title{
	position: relative;left: 0;
	cursor: pointer;

}
.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-items .amrelated-photo-container .amrelated-link img,
.product-info-main .amrelated-content-wrapper .amrelated-pack-list .amrelated-pack-items .amrelated-photo-container .amrelated-link {
    display: block;
    margin: auto;
}
.product-info-main .amrelated-pack-item.-wide,
.product-info-main .amrelated-pack-item.-narrow {
    width: 100%;
}
.product-info-main .amrelated-pack-item.-wide .amrelated-photo-container,
.product-info-main .amrelated-pack-item.-narrow .amrelated-photo-container {
        width: 70px;
    min-width: 70px;
    height: 70px;
    margin-left: 18px;
    position: relative;
    background: #fff;
    border: 1px solid #e8e8e8;
        margin: 0;
}

.product-info-main .amrelated-content-wrapper .amrelated-info .old-price .price {
    font-size: 13px !important;
    line-height: 16px;
    margin-top: -1px !important;
    color: #000000 !important;
}

.catalog-product-view .product-info-main .amrelated-content-wrapper .amrelated-info .old-price .price::after {
      top: 13px;
    left: 16px;
    background: #000 !important;
}



.product-info-main .amrelated-content-wrapper .-narrow.-main {
    display: none;
}


/*ar*/


html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    right: auto;
    left: 0;
}
html[lang="ar"] .product-info-main .amrelated-content-wrapper .amrelated-info {
    margin-left: 0;
    margin-right: 15px;
}
html[lang="ar"] .product-info-main .amrelated-photo-container .amrelated-checkbox+.amrelated-label {
    left: auto;
    right: -30px;
}
html[lang="ar"] .product-info-main .amrelated-pack-item .amrelated-details {
    margin-left: 0px !important;
    margin-right: 20px;
    text-align: right;
}




@media (max-width: 767px){

.product-info-main .amrelated-pack-wrapper .amrelated-content-wrapper .amrelated-photo-container .amrelated-discount span.price {
    font-size: 10px !important;
    color: #fff !important;
}
.catalog-product-view .product-info-main .amrelated-pack-item .amrelated-details .price-box span {
    font-size: 12px !important;

}
.catalog-product-view .product-info-main .amrelated-pack-wrapper .amrelated-title:after{display: none;}
.product-info-main .amrelated-pack-wrapper .amrelated-name a {
    font-size: 12px;
    display: block;
    line-height: 1.2;
    margin-bottom: 4px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper {

  padding: 0

}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
         font-size: 13px;
    padding-right: 23px;
    line-height: 17px;
    letter-spacing: -0.01em;
    padding-left: 8px;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title{
	  font-size: 16px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title img {
    width: 9px;
}

.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    right: 8px;
    top: 13px;
}
.product-info-main .amrelated-pack-item.-collapsed .amrelated-details {
    margin-left: 20px;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title{
padding-right: 8px !important;
	padding-left: 25px !important;
}
.product-info-main .amrelated-photo-container .amrelated-checkbox+.amrelated-label {

    width: 16px;
    height: 16px;

}
.red_bold {
       font-size: 13px;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    right: auto;
    left: 10px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title strong {
    display: block;
    letter-spacing: -0.01em;
}

}

@media (max-width: 450px){
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
         font-size: 11px;

}
.red_bold {
    font-size: 12px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    top: 10px;
}


}


@media (max-width: 415px){
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
         font-size: 10px;

}

html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
         font-size: 12px;

}
.red_bold {
    font-size: 13px;
}
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .arrow-title {
    top: 10px;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .red_bold {
    position: relative;
    top: 1px;
}

}
@media (max-width: 365px){
.product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
     font-size: 9px;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title {
         font-size: 10px;

}
.product-info-main .product-add-form .amrelated-pack-wrapper {
    padding: 0 0;
}
html[lang="ar"] .product-info-main .product-add-form .amrelated-pack-wrapper .amrelated-title .red_bold {
    position: relative;
    top: 1px;
}

}

.product-info-main .amrelated-pack-item:not(.-main) {
    opacity: 1;
    transition: none;
}
.red_bold {
    color: #d51f26;
        font-family: 'LoewNext Heavy' !important;
}
.product-info-main .amrelated-content-wrapper .amrelated-info .amrelated-details .special-price .price {
    color: #ec0101 !important;
}
/*7-10-2021*/
.catalog-product-view .box-tocart .actions div p {
    text-align: center;
    color: #33313b;
    font-size: 15px;
    padding: 10px 0 0;
    margin: 0;
}
.catalog-product-view .box-tocart .actions div p a {
    color: #d51f26;
    padding-left: 5px;
}

@media (max-width:767px) {
.catalog-product-view .box-tocart .actions div p {
       font-size: 12px;
    padding: 0;

}

}
.actions.safari #buy-now{
	width: 100%;
}

</style>
