<!-- @category   Naqel
  @package    Naqel_Shipping -->
<main id="anchor-content" class="page-content">
    <div class="page-main-actions">  
        <form action="<?php echo $block->getUrl('naqel_shipping/bulkcity/save'); ?>" enctype="multipart/form-data" method="POST">
            <a href="<?php echo $block->getUrl('naqel_shipping/bulkcity/downloadsamplecsv');?>">download sample csv file</a><br>
            <fieldset class="fieldset" style="width:50%;">
                <div class="field required">
                 
                    <div class="control">
                        <input type="file" id="fileupload" name="fileupload" class="input-text" />
                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />
                    </div>
                </div>
            </fieldset>
            <br>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</main>