<?php

namespace Vnecoms\PdfPro\Block\Shipping;

class Items extends \Magento\Shipping\Block\Items
{
    protected $helper;

    /**
     * Items constructor.
     *
     * @param \Vnecoms\PdfPro\Helper\Data                      $helper
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Magento\Framework\Registry                      $registry
     * @param array                                            $data
     */
    public function __construct(
        \Vnecoms\PdfPro\Helper\Data $helper,
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\Registry $registry,
        array $data
    ) {
        $this->helper = $helper;
        parent::__construct($context, $registry, $data);
    }

    protected function _toHtml()
    {
        $this->setModuleName($this->extractModuleName('Magento\Shipping\Block\Items'));

        return parent::_toHtml();
    }

//    protected function _prepareLayout()
//    {
//        parent::_prepareLayout(); // TODO: Change the autogenerated stub
//        $this->setTemplate('Magento_Shipping::items.phtml');
//    }

    /**
     * @param object $shipment
     *
     * @return string
     */
    public function getPrintShipmentUrl($shipment)
    {
        if (!$this->helper->getConfig('pdfpro/general/enabled') || !$this->helper->getConfig('pdfpro/general/allow_customer_print')) {
            return parent::getPrintShipmentUrl($shipment);
        }

        return $this->getUrl('pdfpro/order/printShipment', ['shipment_id' => $shipment->getId()]);
    }

    /**
     * @param object $order
     *
     * @return string
     */
    public function getPrintAllShipmentsUrl($order)
    {
        return parent::getPrintAllShipmentsUrl($order);
        if (!$this->helper->getConfig('pdfpro/general/enabled') || $this->helper->getConfig('pdfpro/general/allow_customer_print')) {
            return parent::getPrintAllShipmentsUrl($order);
        }

        return $this->getUrl('pdfpro/order/printShipment', ['order_id' => $order->getId()]);
    }
}
