<?php

namespace Vnecoms\PdfPro\Block\Sales\Order\Creditmemo;

class Items extends \Magento\Sales\Block\Order\Creditmemo\Items
{
    /**
     * @var \Vnecoms\PdfPro\Helper\Data
     */
    protected $helper;

    /**
     * Items constructor.
     *
     * @param \Vnecoms\PdfPro\Helper\Data                      $helper
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Magento\Framework\Registry                      $registry
     * @param array                                            $data
     */
    public function __construct(
        \Vnecoms\PdfPro\Helper\Data $helper,
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\Registry $registry,
        array $data
    ) {
        $this->helper = $helper;
        parent::__construct($context, $registry, $data);
    }

    protected function _toHtml()
    {
        $this->setModuleName($this->extractModuleName('Magento\Sales\Block\Order\Creditmemo\Items'));

        return parent::_toHtml();
    }

//    protected function _prepareLayout()
//    {
//        parent::_prepareLayout(); // TODO: Change the autogenerated stub
//        $this->setTemplate('Magento_Sales::order/creditmemo/items.phtml');
//    }

    /**
     * @param object $creditmemo
     *
     * @return string
     */
    public function getPrintCreditmemoUrl($creditmemo)
    {
        if (!$this->helper->getConfig('pdfpro/general/enabled') || !$this->helper->getConfig('pdfpro/general/allow_customer_print')) {
            return parent::getPrintCreditmemoUrl($creditmemo);
        }

        return $this->getUrl('pdfpro/order/printCreditmemo', ['creditmemo_id' => $creditmemo->getId()]);
    }

    /**
     * @param object $order
     *
     * @return string
     */
    public function getPrintAllCreditmemosUrl($order)
    {
        return parent::getPrintAllCreditmemosUrl($order);
        if (!$this->helper->getConfig('pdfpro/general/enabled') || $this->helper->getConfig('pdfpro/general/allow_customer_print')) {
            return parent::getPrintAllCreditmemosUrl($order);
        }

        return $this->getUrl('pdfpro/order/printCreditmemo', ['order_id' => $order->getId()]);
    }
}
