<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Mostviewed
 */
?>
<?php

use Magento\Catalog\Pricing\Price\FinalPrice;

// @codingStandardsIgnoreFile

/** @var \Amasty\Mostviewed\Block\Product\BundlePack $block */
/** @var \Amasty\Mostviewed\Api\Data\PackInterface $pack */
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$isEmpty = true;
?>
<?php foreach ($block->getBundles() as $pack) : ?>
    <?php if ($childIds = $pack->getProductIds()) :?>
        <?php
            $packKey = $pack->getPackId() . '-' . uniqid();
            $items = $block->getProductItems($childIds);
            if (!$items) {
                continue;
            }
            $itemsCount = count($items);
            $isWideLayout = $itemsCount <= 3 && !$block->isCheckoutPage();
            $itemClass = $isWideLayout ? '-wide' : '-narrow';
            $config = $block->getPackJsonConfig($pack, $items);
            $discountResult = $block->getDiscountResult($config);
        ?>
        <div class="amrelated-pack-wrapper" data-amrelated-js="pack-wrapper" id="amrelated-pack-<?= /* @noEscape */ $packKey;?>">
            <div class="amrelated-title" data-amrelated-js="pack-title">
                <strong><?= $block->escapeHtml(__('Add this Product and get an extra discount!'))?> - <span class="red_bold"> <?php echo $config['discount_amount']; if($config['discount_type'] == 1 ){ echo '%'; }else{ echo __('SAR');} ?> </span></strong>
				<span class="arrow-title"><img src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl(); ?>lEHzMw8.png" /></span>
            </div>

            <div class="amrelated-content-wrapper">
                <div class="amrelated-pack-list <?= /* @noEscape */ $itemClass;?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item) : ?>
                        <?php $isParent = $iterator == 1; ?>
						
                        <?php if ($iterator == 2 && $isWideLayout) : ?>
                            <div class="amrelated-pack-items -selected" data-amrelated-js="pack-container">
                                <div class="amrelated-background" data-amrelated-js="selected-background"></div>
                        <?php endif;?>
                            <div class="amrelated-pack-item <?= /* @noEscape */ $itemClass;?><?= /* @noEscape */ $isParent ? ' -main' : ' -selected'?>"
                                 data-amrelated-js="pack-item"
                                 data-product-id="<?= /* @noEscape */ $item->getId()?>"
                            >
                                <div class="amrelated-info">
                                    <div class="amrelated-photo-container">
                                        <?php if (!$isParent) : ?>
                                            <?php $productQty = $pack->getChildProductQty($item->getId()) ?>
                                            <input type="checkbox" class="amrelated-checkbox"
                                                   id="amrelated-checkbox<?= /* @noEscape */ $item->getId() . '-' . $packKey ?>"
                                                   name="amrelated_products[<?= /* @noEscape */ $item->getId() ?>]"
                                                   data-amrelated-js="checkbox"
                                                   value="<?= (int) $productQty  ?>" />
                                            <label for="amrelated-checkbox<?= /* @noEscape */ $item->getId() . '-' . $packKey ?>"
                                                   class="amrelated-label"></label>
                                        <?php endif; ?>
                                        <a href="<?= $block->escapeUrl($block->getImageUrl($item)) ?>"
                                           class="" <?php if (!$isParent) : ?> data-fancybox="gallery<?php echo $item->getId(); ?>" <?php endif; ?>>
                                            <img src="<?= $block->escapeUrl($block->getImageUrl($item)) ?>"
                                                 class="amrelated-photo"
                                                 alt="<?= $block->escapeHtml($item->getName()) ?>">
                                            <?php if (!$isParent && $productQty > 1) : ?>
                                            <span class="amrelated-qty"><?= (int) $productQty ?></span>
                                            <?php endif; ?>
                                        </a>
										<div class="hide_images" style="display:none;" >
										<?php
											$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
											$product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getId());        
											$images = $product->getMediaGalleryImages();
											foreach($images as $child){ ?>
											<a href="<?php echo $child->getUrl(); ?>" class="" <?php if (!$isParent) : ?> data-fancybox="gallery<?php echo $item->getId(); ?>" <?php endif; ?>>
												<img src="<?php echo $child->getUrl(); ?>" >
											</a>
										<?php } ?>
										</div>
                                        <?php $discountHtml = $block->getProductDiscount($pack, $isParent); ?>
                                        <?php if ($discountHtml) : ?>
                                            <div class="amrelated-discount -product">
                                                <?= /* @noEscape */ $discountHtml ?>
                                                <?php if (!$isParent && $productQty > 1) : ?>
                                                    <?= $block->escapeHtml(__('each')) ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="amrelated-details">
                                        <div class="amrelated-name">
                                            <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                               href="javascript:void(0)"
                                               class="amrelated-link" 
                                            >
                                                <?= $block->escapeHtml($item->getName()) ?>
                                            </a>
                                        </div>

                                        <?php if ($templateType) : ?>
                                            <?= /* @noEscape */ $block->getReviewsSummaryHtml($item, $templateType) ?>
                                        <?php endif; ?>
										<?php
											$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
											$productCollection = $objectManager->create('Magento\Catalog\Model\Product')->loadByAttribute('sku', $item->getSku());
											$productPriceBySku = $productCollection->getPrice();
										?>
										<div class="product-info-price"><div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $item->getId() ?>" data-price-box="product-id-<?php echo $item->getId() ?>">
											<span class="special-price">
											<span class="price-container price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
											<span class="price-label"><?php echo __('Special Price');?></span>
											<?php if($config['discount_type'] == 1 ){ $special =  $productPriceBySku * ((100-$config['discount_amount']) / 100); } ?>
											<?php if($config['discount_type'] == 0 ){ $special =  $productPriceBySku - $config['discount_amount']; } ?>
											<span id="product-price-<?php echo $item->getId() ?>" data-price-amount="<?php echo $special ?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo number_format((float)$special, 2, '.', '')?> <?php echo __('SAR'); ?> </span></span>
											<meta itemprop="price" content="76">
											<meta itemprop="priceCurrency" content="SAR">
											</span>
											</span>
											<span class="old-price">
											<span class="price-container price-final_price tax weee">
											<span class="price-label"><?php echo __('Regular Price')?></span>
											<span id="old-price-<?php echo $item->getId() ?>" data-price-amount="<?php echo number_format((float)$productPriceBySku, 2, '.', '') ?>" data-price-type="oldPrice" class="price-wrapper "><span class="price"><?php echo  number_format((float)$productPriceBySku, 2, '.', '') ?> <?php echo __('SAR'); ?></span></span>
											</span>
											</span>
										</div>
										</div>
									</div>
                                </div>
                            </div>
                        <?php if ($iterator++ != $itemsCount) :?>
                            <!--<span class="amrelated-plus">+</span>-->
                        <?php elseif ($isWideLayout) :?>
                            </div>
                        <?php endif;?>
                    <?php endforeach; ?>
                </div>
                <!--<span class="amrelated-equal">=</span>-->
                <div class="amrelated-summary-content">
                    <div class="amrelated-price-wrapper">
                        <div class="amrelated-discount -summary">
                            <?= $block->escapeHtml(__('Save'));?>
                            <span class="amount" data-amrelated-js="bundle-price-discount">
                                <?= /* @noEscape */ $block->priceOutput($discountResult['discount'])?>
                            </span>
                        </div>
                        <div class="main price" data-amrelated-js="bundle-final-price">
                            <?= /* @noEscape */ $block->priceOutput($discountResult['final_price']) ?>
                        </div>
                    </div>
                    <?php $isEmpty = false;?>
                    <div class="amrelated-tocart-wrapper">
                        <button class="action primary" type="button"
                                data-amrelated-js="add-to-cart"
                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#amrelated-pack-<?= /* @noEscape */ $packKey;?>": {
                    "Amasty_Mostviewed/js/ampack":<?= /* @noEscape */ $block->encode($config) ?>
                }
            }
        </script>
    <?php endif;?>
<?php endforeach;?>

<?php if (!$isEmpty) : ?>
    <script type="text/x-magento-init">
        {
            "[data-amrelated-js='add-to-cart']": {
                "Amasty_Mostviewed/js/ampackcart":<?= /* @noEscape */ $block->getJsonConfig();?>
            }
        }
    </script>
<?php endif;?>
<script>
require(['jquery'], function(jQuery){
	jQuery('.amrelated-pack-wrapper .amrelated-content-wrapper').removeClass('open--tab');
		jQuery('body').on('click', '.amrelated-pack-wrapper .amrelated-title', function(){
			jQuery(this).toggleClass('open--accordian');
			jQuery('.amrelated-pack-wrapper .amrelated-content-wrapper').toggleClass('open--tab');
		});	 
		
		if (navigator.userAgent.indexOf('Safari') && !navigator.userAgent.indexOf('Chrome')) {
			jQuery('body').on('click', '.amrelated-pack-wrapper .amrelated-info', function(){
			jQuery(this).find('.amrelated-label').click();
		});	
		}else {
			jQuery('body').on('click', '.amrelated-pack-wrapper .amrelated-details', function(){
				jQuery(this).parents('.amrelated-info').find('.amrelated-label').click();
			});	
		}
});
			
</script>
<style>
.amrelated-details .price-wrapper[data-price-type="oldPrice"] span.price{
	top: 0 !important;
}
.amrelated-pack-item .amrelated-name{
    clear: both;
}
.amrelated-details{
	clear: both;
}
.amrelated-details .product-info-price {
    overflow: hidden;
    clear: both;
}
</style>
