<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Mostviewed
 */
?>
<?php
/**
 * @var \Amasty\Mostviewed\Block\Widget\Related $block
 * @codingStandardsIgnoreFile
 */
?>
<style type="text/css">
    .block-products-list .slick-list .price-box.price-final_price .old-price span.price:after {
    content: "";
    display: block;
    position: absolute;
    width: 68%;
    height: 1px;
    background: red;
    top: 50%;
    transform-origin: top;
    transform: rotate(338deg);
    left: 8px;
}
</style>
<?php 
    $themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
    $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
    $size = $themeHelper->getImageSize($this->getRatio());
    $padding = $themeHelper->getImagePadding($this->getRatio());
    $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); 
    $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
    $image_hover = 'product_thumbnail_image';
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_aHelper = $this->helper('MGS\AjaxCart\Helper\Data');
    $animationType = $_aHelper->getConfig('ajaxcart/additional/animation_type');
    $swatches = null;
?>
<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'related_products_content';
    $items = $block->getProductCollection()->getItems();

    $isSlider = true;
    $tagWrap = $isSlider ? 'div' : 'ol';
    $tag = $isSlider ? 'div' : 'li';

    $showWishlist = true;
    $showCompare = true;
    $showCart = $block->getAddToCart();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    
    <div class="block <?= /* @noEscape */ $block->getCssClass() ?> amrelated-grid-wrapper block-products-list <?= /* @noEscape */ $mode ?>"
         id="amrelated-block-<?= (int)$block->getGroupId();?>"
    >
        <?php if ($block->getTitle()) : ?>
        <!-- <div class="content-heading" >
            <h3 class="title text-uppercase">
            <span id="block-related-heading" ><?php // $block->escapeHtml(__($block->getTitle())) ?></span>
            </h3>
        </div> -->
        <div class="tab_content_header">
            <p class="tab_view_all"><a href="#"><?= __('Show All') ?></a></p>
            <p class="tab_title"><?= $block->escapeHtml(__($block->getTitle())) ?></p>
        </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <<?= /* @noEscape */ $tagWrap?> class="product-items <?= /* @noEscape */ $type ?>" <?= /* @noEscape */ $isSlider ? 'data-amrelated-js="slider"' : ''?>>
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item) : ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '' : '</' . $tag . '>' ?><<?= /* @noEscape */ $tag?> class="product-item">
                        <?php $_productNameStripped = $block->stripTags($block->escapeHtml($item->getName()), null, true); ?>
                        <?php
                            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                            $productImage = $_imagehelper->init($item, $image)->resize($size['width'], $size['height'])->getUrl();
                            $productImageHover = $_imagehelper->init($item, $image_hover)->resize($size['width'], $size['height'])->getUrl();
                        ?>
                        <div class="product-top">
                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" style="padding-bottom: <?php echo $padding ?>;" class="product photo product-item-photo" tabindex="-1">
                                <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> owl-lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
                                <?php if(basename($item->getData('thumbnail')) !=  'no_selection'): ?>
                                    <?php if(basename($item->getData('thumbnail')) != basename($item->getData('small_image'))): ?>
                                        <img src="<?php echo $productImageHover; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-hover-show<?php if($lazyLoad): ?> owl-lazy<?php endif ?>" data-src="<?php echo $productImageHover ?>"/>
                                    <?php endif ?>
                                <?php endif ?>
                            </a>
                            <?php echo $themeHelper->getProductLabel($item) ?>
                            <ul class="actions-link">
                                <li class="hidden-sm hidden-xs">
                                    <?php echo $quickViewHelper->aroundQuickViewHtml($item); ?>
                                </li>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                    <li>
                                        <button class="action towishlist"
                                            title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            data-title="<?php echo __('Add to Wish List') ?>"
                                            aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                            data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($item); ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                            <i class="pe-7s-like"></i>
                                        </button>
                                    </li>
                                <?php endif; ?>
                                <?php if($showCart): ?>
                                    <?php if ($item->isSaleable()): ?>
                                        <li>
                                        <?php 
                                                $has_option = 0;
                                                //var_dump($item->getTypeId());
                                                if($item->getTypeId() == 'simple'){
                                                    $data = $item->getData();
                                                    $has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
                                                }
                                            ?>
                                            <?php if($animationType == 'cartshow' && ($item->getTypeId() == 'configurable' || $item->getTypeId() == 'bundle' || $item->getTypeId() == 'grouped' || ($item->getTypeId() == 'simple' && $has_option == 1) )): ?>
                                                <button class="action btn-cart tocart" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="window.location.href = '<?php echo $item->getProductUrl() ?>'">
                                                    <span class="icon pe-7s-shopbag d-sm-non"></span>
                                                    <span class="product-item-link">
                                                        <?php echo __('Add to cart'); ?>
                                                    </span>
                                                </button>   
                                            <?php else: ?>
                                                <button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span class="icon pe-7s-shopbag"></span>
                                                    <span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif ?>
                                        </li>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                <?php if($block->getAddToCompareUrl() && $showCompare): ?>
                                    <li>
                                        <button class="action tocompare"
                                            title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                            data-title="<?php echo __('Add to Compare') ?>"
                                            aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                            data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($item); ?>'
                                            role="button">
                                            <i class="pe-7s-graph3"></i>
                                        </button>
                                    </li>
                                <?php endif ?>
                            </ul>
                            <?php if($showCart)://if ($themeHelper->getStoreConfig('mpanel/catalog/disable_add_to_cart') == 0 && $themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect') == 0): ?>
								<?php if ($item->isSaleable()): ?>
									<div>
										<?php $postParams = $block->getAddToCartPostParams($item); ?>
										<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
											<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
											<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
											<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
											<?php 
												$has_option = 0;
												if($item->getTypeId() == 'simple'){
													$data = $item->getData();
													$has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
												}
											?>
											<?php if($animationType == 'cartshow' && ($item->getTypeId() == 'configurable' || $item->getTypeId() == 'bundle' || $item->getTypeId() == 'grouped' || ($item->getTypeId() == 'simple' && $has_option == 1) )): ?>
                                                <button class="action btn-cart tocart" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" onclick="window.location.href = '<?php echo $item->getProductUrl() ?>'">
													<span class="icon pe-7s-shopbag d-sm-non"></span>
													<span class="product-item-link">
														<?php echo __('Add to cart'); ?>
													</span>
												</button>	
											<?php else: ?>
												<button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<span class="icon pe-7s-shopbag"></span>
													<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php endif ?>
										</form>
									</div>
								<?php endif ?>
							<?php endif ?>
                        </div>
                        <div class="product details product-item-details">
                            <h5 class="product name product-item-name">
                                <a class="product-item-link"
                                    href="<?php /* @escapeNotVerified */ echo $item->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($item, $item->getName(), 'name'); ?>
                                </a>
                            </h5>
                            <?php if(!$themeHelper->getStoreConfig('mpanel/catalog/review')): ?>
                                
                                <?php 
                                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                                    echo $block->getReviewsSummaryHtml($item, $templateType,true); 
                                ?>
                            <?php endif ?>
                            
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($item) ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($item)->setTextSwatch($swatches)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                            <?php //echo $item->getSku() ?>   
                            
                        </div>
                        <?= /* @noEscape */ ($iterator == count($items)+1) ? '</' . $tag . '>' : '' ?>

                    <?php endforeach ?>
                </<?= /* @noEscape */ $tagWrap?>>
            </div>
        </div>
    </div>
    <?php if ($isSlider) : ?>
        <script type="text/javascript">
            require([
                "jquery",
                "Amasty_Base/vendor/slick/slick.min"
            ], function ($) {
                $('#amrelated-block-<?= /* @noEscape */ (int)$block->getGroupId();?> [data-amrelated-js="slider"]').slick(
                    {
                        dots:true,
                        infinite: true,
                        slidesToShow: 4,
                        slidesToScroll: 1,
                        rtl: true,
                        responsive: [
                            {
                                breakpoint: 1280,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 3
                                }
                            },
                            {
                                breakpoint: 992,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 2
                                }
                            },
                            {
                                breakpoint: 500,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 1
                                }
                            }
                        ]
                    }
                );
            });
        </script>
    <?php endif; ?>
<?php endif;?>
