<?php
	$citySearchPlaceHolder = __('search your city');
?>

<input type="hidden" name="cityurl" value="<?php echo $this->getUrl('couriermanager/index/index') ?>" />
<input type="hidden" name="districturl" value="<?php echo $this->getUrl('couriermanager/index/district') ?>" />

<script type="text/javascript">
	require(['jquery', 'Evincemage_City/js/select2'], function($)
	{ 
     	 $(document).ready(function(){
     	 	console.log('testt');
     	 	var mySelectIntervalCity = setInterval(function()
     	 	{ 
    			//code goes here that will be run every 5 seconds. 
    			if($( "select[name='city']" ).length)
    			{
    				console.log('testt 5');
    				//console.log($('.select').select2());
    				$( "select[name='city']" ).select2().on('select2:open', function(e){
    					$('.select2-search__field').attr('placeholder', "<?= __('search your city') ?>");
					});
    				clearInterval(mySelectIntervalCity);	
    			}
    			   
			}, 5000);

			var mySelectIntervalDist = setInterval(function()
     	 	{ 
    			//code goes here that will be run every 5 seconds. 
    			if($( "select[name='district']" ).length)
    			{
    				console.log('testt 5');
    				//console.log($('.select').select2());
    				$( "select[name='district']" ).select2();
    				clearInterval(mySelectIntervalDist);	
    			}
    			   
			}, 5000);

			var mySelectIntervalStreet = setInterval(function()
     	 	{ 
    			//code goes here that will be run every 5 seconds. 
    			if($('input[name^="street"]').length)
    			{
    				$('input[name^="street"]').attr('placeholder',"<?= __('Street Name/ House/Apartment No.') ?>")
    				clearInterval(mySelectIntervalStreet);	
    			}
    			   
			}, 5000);

			
			
     	 	
     	 });	
 	})
</script>



