<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $footer = $helper->getStoreConfig('mgstheme/general/footer') ?>

<?php if($footer == '' || $footer == 'footer_1'): ?>
    <div class="footer-container">
        <div class="middle-footer">
            <div class="container">
			
                <div class="row">
                    <div class="col-sm-12 col-xs-12 social_icons">
					 <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
					</div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_payment')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_subscribe -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_subscribe')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 copyright">
                        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                    </div>
                </div>
            </div>
        </div>
        <div class="show-mobile">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_sticky_mobile')->setCanUsePanel($canUsePanel)->toHtml() ?>
        </div>
    </div>
<?php elseif($footer == 'footer_2'): ?>
    <div class="footer-container">
        <div class="top-footer">
            <div class="container">
                <!-- Static block: footer_block_newsletter_top -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter_top')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </div>
        </div>
        <div class="middle-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="clearfix visible-sm"></div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <!-- Static block: footer_block_instagram -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_instagram')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-7 col-sm-12 col-xs-12 copyright">
                        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                    </div>
                    <div class="col-lg-6 col-md-5 col-sm-12 col-xs-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php elseif($footer == 'footer_3'): ?>
    <div class="footer-container">
        <div class="bottom-footer">
            <div class="container">
                <!-- Static block: footer_logo_and_social -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_logo_and_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
                <!-- Static block: claue_footer3_custom_menu -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('claue_footer3_custom_menu')->setCanUsePanel($canUsePanel)->toHtml() ?>
                <div class="copyright">
                    <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                </div>
            </div>
        </div>
    </div>
<?php elseif($footer == 'footer_4'): ?>
    <div class="footer-container">
        <div class="top-footer">
            <div class="container">
                <!-- Static block: footer_block_newsletter_top -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter_top')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </div>
        </div>
        <?php
            // Background Image Left Footer
            $backgroundImage = "";
            $staticImage =  $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_background_image')->toHtml();
            if($staticImage != null) {
                preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $staticImage, $matches);
                if(!empty($matches[1][0])){
                    $backgroundImage = $matches[1][0];
                }
            }
        ?>
        <div class="middle-footer-container">
            <div class="middle-col" <?php if($backgroundImage != ""): ?>style="background-image:url(<?php echo $backgroundImage ?>);"<?php endif ?>>
                <div class="visible-builder text-center">
                    <a class="btn btn-default btn-xs" href="javascript:void(0)" data-toggle="modal" data-target="#change_bg_footer">Change Background</a>
                    <div id="change_bg_footer" class="modal fade" style="display: none;" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"><button class="close" type="button" data-dismiss="modal">x</button>
                                <div class="modal-body">
                                    To change background-image of this col, you can create a static block with identifier footer_background_image. Insert an image to content of this static block.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="middle-footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 margin-bottom40">
                                <!-- Static block: footer4_contact_us -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer4_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_categories -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_infomation -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                            <div class="col-lg-4 col-sm-4 col-xs-12 margin-bottom40">
                                <!-- Static block: footer_block_quick_link -->
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bottom-footer">
                    <div class="container">
                        <div class="copyright">
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        </div>
                    </div>
                </div>
            </div>
            <div id="footer-map" class="footer-map">
                <!-- Static block: footer_block_image_map -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_image_map')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </div>
        </div>
    </div>
<?php endif ?>

<script type="text/javascript">
    require([
        'jquery',
        'mgs/owlcarousel'
        ], function ($) {
        var owlinstagram69741497285959 = $('#instagram-widget69741497285959').owlCarousel({
            items: 6,
            autoplay: true,
            autoplayHoverPause: true,
            nav: false,
            rtl: true,
            dots: false,
            loop: true,
            autoHeight: true,
            navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
            responsive:{
                0:{
                    items:2
                },
                480:{
                    items:4
                },
                768: {
                    items:4
                },
                992:{
                    items:6								
					}
                }
            });
        var owlinstagram69741497285959 = $('#brand-widget123').owlCarousel({
            items: 6,
            autoplay: true,
            autoplayHoverPause: true,
            nav: false,
            rtl: true,
            dots: false,
            loop: true,
            autoHeight: true,
            margin: 20,
            navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
            responsive:{
                0:{
                    items:4,
					  nav: true
                },
                480:{
                    items:4,
					  nav: true
                },
                768: {
                    items:4,
					  nav: true
                },
                    992:{
                    items:5							
                }
            }
        });
        $("#mgs-slider-16945332161597733001").on('initialized.owl.carousel', function(event) {
            setTimeout(function(){
                $("#page-header-sliders").addClass('loaded');
            }, 500);
        });
                
        $("#mgs-slider-16945332161597733001").owlCarousel({
            items: 1,
            rtl: RTL,
            loop: true,
            nav: false,
            dots: true,
            autoplayTimeout: 5000,
            autoplay: true,
            autoplayHoverPause: false,
            animateOut: 'slideOutRight',
            animateIn: 'slideInLeft',
            responsive:{
                0:{
                    nav: false,
                    dots: true
                },
                992:{
                    nav: false,
                    dots: true 
                }
            }
        });
		
		
		
    });
</script>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var menu = this.nextElementSibling;
    if (menu.style.display === "block") {
      menu.style.display = "none";
    } else {
      menu.style.display = "block";
    }
  });
}
</script>

<div id="loadingload" style="display:none;">
  <img id="loading-image" src="<?php echo $this->getViewFileUrl('images/loader.svg'); ?>" alt="Loading..." />
</div>
<style>
#block-gift-card-discount{
    display: none;
}    
#loadingload {
  position: fixed;
  display: block;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  text-align: center;
  opacity: 0.9;
  background-color: #fff;
  z-index: 99;
}

#loading-image {
  position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 100;
    height: 100px;
    width: 100px;
    margin: auto;
}
#s-521c94d0-c734-4b9e-ab6f-e6d921e72393 {
    min-height: 50px;
}
.shg-box>.shg-box-content {
    z-index: 4;
    position: relative;
}
.shg-box-video-wrapper {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
    z-index: -1;
}
.shg-box-overlay {
    background-color: #fff;
    opacity: 0;
}
.shg-box-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 3;
    pointer-events: none;
}
.video-wrapper {
    position: relative;
    overflow: hidden;
    max-width: 100%;
    padding-bottom: 56.25%;
    height: 0;
    height: auto;
}

.shogun-video {
    position: relative;
    display: block;
    height: 0;
    padding: 0;
    overflow: hidden;
}
.shogun-video-16x9 {
    padding-bottom: 56.25%;
}
.shogun-root iframe {
    display: initial;
}
.video-wrapper iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
.shogun-video-embed {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: 0;
}
iframe, img {
    max-width: 100%;
}
.shg-c, .shg-box {
    background-attachment: scroll !important;
}

.end-footer {
    justify-content: space-between;
    display: flex;
}

.footer-item {
    width: 30%;
}

.footer-item:nth-child(1) img {
    width: 60%;
}

.footer-item:nth-child(3) img {
    width: 27%;
}

.footer-item:nth-child(2) {
    text-align: right;
}
</style>
<script>
require(['jquery'], function ($) {
	 /*setTimeout(function() {
		$('#loadingload').hide();
	},2000);*/

	jQuery(".change_language").on('click',function(e){
		e.preventDefault(0);
		jQuery("#switcher-language").find("li.switcher-option").find('a').click()
	});
});
</script>