<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<ul class="opc-progress-bar">
    <!-- ko foreach: { data: steps().sort(sortItems), as: 'item' } -->
    <li class="progress-bar-shipping opc-progress-bar-item _complete" data-bind="css: item.isVisible() ? '_active' : ($parent.isProcessed(item) ? '_complete' : '')">
        <span data-bind="i18n: item.title, click: $parent.navigateTo"><?= __('العنوان وطرق الشحن') ?></span>
    </li>

    <li class="opc-progress-bar-item _complete" data-bind="css: item.isVisible() ? '_active' : ($parent.isProcessed(item) ? '_complete' : '')">
        <span data-bind="i18n: item.title, click: $parent.navigateTo"><?= __('الدفع') ?></span>
    </li>
    <!-- /ko -->
    <li class="progress-bar-shipping-success opc-progress-bar-item _complete">
        <span data-bind="i18n: item.title, click: $parent.navigateTo"><?= __('Success') ?></span>
    </li>
</ul>

<div class="checkout-success">
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>