<?php
// @codingStandardsIgnoreFile
?>
<?php
$customerEmail = '';
$customerPhone = '';
$customerInfo = $this->getCustomerInfo();
if(isset($customerInfo)){
    $customerEmail = $customerInfo['email'];
    $customerPhone = $customerInfo['phone'];
}

$ipv4Address = $_SERVER['REMOTE_ADDR'];
$hashedString = hash('sha256', $ipv4Address);
$userAgent = $_SERVER['HTTP_USER_AGENT'];
?>
<?php if ($this->isEnabled()) : ?>
    <?php $dataLayerObject = $this->getDataLayerAsJson(); ?>
    <script>
        window.getWpCookie = function(name) {
            match = document.cookie.match(new RegExp(name + '=([^;]+)'));
            if (match) return decodeURIComponent(match[1].replace(/\+/g, ' ')) ;
        };

        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({'snap_email': '<?php echo $customerEmail ?>'});
        window.dataLayer.push({'snap_phone_number': '<?php echo $customerPhone ?>'});
        window.dataLayer.push({'user_agent': '<?php echo $userAgent ?>'});
        window.dataLayer.push({'ip_address': '<?php echo $ipv4Address ?>'});
        window.dataLayer.push({'first_name': '<?php echo $customerInfo['first_name'] ?>'});
        window.dataLayer.push({'last_name': '<?php echo $customerInfo['last_name'] ?>'});
        window.dataLayer.push({'zipcode': '<?php echo $customerInfo['zip_code'] ?>'});
        <?php if ($dataLayerObject != '[[]]') : ?>
        var dlObjects = <?php echo $dataLayerObject; ?>;
        for (var i in dlObjects) {
            window.dataLayer.push(dlObjects[i]);
        }
        <?php endif; ?>
        var wpCookies = [<?php echo $this->getWpCookiesForJs(); ?>];
        wpCookies.map(function(cookieName) {
            var cookieValue = window.getWpCookie(cookieName);
            if (cookieValue) {
                var dlObject = {};
                dlObject[cookieName.replace('wp_', '')] = cookieValue;
                window.dataLayer.push(dlObject);
            }
        });
    </script>
<?php endif; ?>