<!-- @category   Naqel
  @package    Naqel_Shipping -->
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $NaqelCollection = $objectManager->create('\Naqel\Shipping\Model\WaybillFactory');
?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">

        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>

                    <tr>
                        
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                            </a>
                            <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                                </a>
                            <?php endif ?>
                          
                          <?php 
                          // show track order btn if shippung method is  naqel_shipping_naqel_shipping and order shipment is generated
                          
                          
                          //naqelshipping_naqelshipping
                           if(($_order->getShippingmethod()) && ($_order->hasShipments() == 1)):

                            $waybill_data = $NaqelCollection->create()->getCollection ()->addFieldToFilter('entity_id', array('eq' => $_order->getId()))->getData();

                            if(isset($waybill_data[0]['waybill_no']) && $waybill_data[0]['waybill_no'] !=''): 
                            
                          ?>
                            <a href="javascript:void(0);" order-id ="<?php echo $_order->getId();?>"   id="track_naqel_order" class="action track"  title="Naqel shipping">
                                <span><?= /* @escapeNotVerified */ __('Track Order') ?></span>
                            </a>
                           <?php endif; endif;?> 
                        </td>

                        

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>


<div id="popup-modal">
     <style type="text/css">
        @import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css");
           
            .track_tbl td.track_dot {
                width: 50px;
                position: relative;
                padding: 0;
                text-align: center;
            }
            .track_tbl td.track_dot:after {
                content: "\f111";
                color: #11ce11;
                font-family: FontAwesome;
                position: absolute;
                margin-left: -5px;
                top: 15px;
            }
            .track_tbl td.track_dot span.track_line {
                background: green;
                width: 3px;
                min-height: 50px;
                position: absolute;
                height: 101%;
            }
            .track_tbl tbody tr:first-child td.track_dot span.track_line {
                top: 30px;
                min-height: 25px;
            }
            .track_tbl tbody tr:last-child td.track_dot span.track_line {
                top: 0;
                min-height: 25px;
                height: 10%;
            }
    </style>
    <div class="ajaxresponse table-responsive"></div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Order Tracking',
                buttons: [{
                    text: $.mage.__('Exit'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $(document).on("click","#track_naqel_order",function(){

                var entity_id = $(this).attr('order-id');
                
                var ajaxURL = '<?php echo $block->getUrl("naqel/index/index"); ?>';

                  $.ajax({
                    type: "POST",
                    url: ajaxURL,
                    data: {entity_id:entity_id},
                    success: function(result){
                        
                        $(".ajaxresponse").html(result);
                        $('#popup-modal').modal('openModal');
                    },
                    error: function(jqXHR, textStatus, errorThrown){

                        console.log(errorThrown);
                    },
                    beforeSend: function(jqXHR, settings){
                        $('body').trigger('processStart');        
                    },
                    complete: function(jqXHR, textStatus){
                        $('body').trigger('processStop');
                    }
                });  

                  
                
            });
            
        }
    );
</script>

